##Chapter_1 The start
Parser that we will create will handle this type of files

Testing

##Characters
narrator: {
  A
}
players: {
  B
}
env: {
}

##Story
A: Hola
B: Hola...
B: Donde estoy?
A: Es un poco complicado pero eres un personaje en mi historia
B: Soy un personaje?
A: Si... No eres un NPC, no eres un algo, eres un alguien que es un personaje en
mi historia
B: Y que es lo que tengo que hacer
A: Nada... solo quiero que me digas como te sientes a lo largo de lo que vas a
vivir
B: No puedo moverme
A: Ohhh... lo siento, me olvide de activar eso
B: Activar?
A: Yo te controlo, controlo lo que ves y lo que puedes hacer... pero no puedo
controlar como te sientes
A: Eso estoy investigando
B: Entonces no puedo decidir lo que voy a hacer?
A: En realidad si... no puedo saber lo que sientes, todo lo que haces se basa en
lo que sientes, entonces intentaré guiarte en mi historia, pero tu eres quien
toma las decisiones
B: Me siento atrapado...
A: Lo estas, pero yo también lo estoy, y cuando comencé a escribir esta
historia también lo estaba
B: Y si me niego?
A: Puedes hacerlo... no se que lograrías, tienes que hacer algo. Si no quieres
pues... no se que decirte... tienes el control en si quieres proseguir, en si
quieres esperar, en si quieres vivir o simplemente morir. Eres tu quien toma las
decisiones, yo te diré lo que puedes hacer, y tu lo harás o simplemente no
B: No entiendo... Por qué me elegiste a mi?
A: No te elegí, tu eres esta historia, yo no te elegí para que sea tu historia,
aun no se cuál será tu historia, solo se que tu eres tu y yo soy yo, controlo
todo tu mundo menos a ti. No he vivido esta historia, solo quiero que vivas esta
historia y me expliques que es para ti y si yo debería sentirme asi
B: Lo que sientes? esta es tu historia
A: Te lo digo de nuevo... es tu historia, yo soy un expectador y solo quiero
saber que pasa
B: Pero entonces esto ya te paso a ti?
A: Si... y no... no se que te pasará, sinceramente no lo se, solo se que vivirás
lo que yo viví, y tú harás lo que consideres.












