[package]
name = "our_journey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
parser = []

[dependencies]
sdl2 = "0.36"
